- name: 复制 kubelet
  copy:
      src: /{{ local_dir }}/kubernetes/server/bin/kubelet
      dest: "{{ bin_dir }}"
      mode: 755

- name: 新建日志文件
  file:
    path: "{{ log_dir }}/{{ log_file }}"
    state: touch
- name: 新建工作目录
  file:
    path: "{{ kubelet_dir }}"
    state: directory

- name: 复制 kubelet.service
  template:
          src: kubelet.service.j2
          dest: /usr/lib/systemd/system/kubelet.service
- name: 复制 kubelet 配置文件
  template:
          src: kubelet.j2
          dest: "{{config_dir }}/{{ config_file }}"
- name: 复制 kubelet-config.yaml
  template:
          src: kubelet-config.yaml.j2
          dest: "{{config_dir }}/{{ kubelet_confing }}"

- name: 重载
  command: systemctl daemon-reload
 
- name: 启动 kubelet
  service:
          name: kubelet
          state: started
          enabled: yes
