- name: 安装 ipvsadm
  yum:
      state: present
      name: ipvsadm
- name: 安装 conntrack
  yum:
      state: present
      name: conntrack
      
- name: 复制 kube-proxy
  copy:
      src: /{{ local_dir }}/kubernetes/server/bin/kube-proxy
      dest: "{{ bin_dir }}"
      mode: 755

- name: 复制 kube-proxy.service
  template:
          src: kube-proxy.service.j2
          dest: /usr/lib/systemd/system/kube-proxy.service
- name: 复制 proxy 配置文件
  template:
          src: proxy.j2
          dest: "{{ config_dir }}/{{ config_file }}"

- name: 复制 proxy-config.yaml
  template:
          src: proxy-config.yaml.j2
          dest: "{{ config_dir }}/{{ proxy_confing }}"         
- name: 新建日志文件
  file:
    path: "{{ log_dir }}/{{ log_file }}"
    state: touch

- name: 重载
  command: systemctl daemon-reload
 
- name: 启动 kube-proxy
  service:
          name: kube-proxy
          state: started
          enabled: yes
